version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.4
    steps:
      - checkout
      - run: make
      - run: make clean
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
