version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.4
    steps:
      - checkout
      - run: VERBOSE=1 make all
      - run: VERBOSE=1 make test
      - run: VERBOSE=1 make clean
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
