version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.4
    steps:
      - checkout
      - run: DEBUG=1 VERBOSE=1 make
      - run: DEBUG=1 VERBOSE=1 make test
      - run: DEBUG=1 VERBOSE=1 make clean
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
