// Code generated by protoc-gen-go. DO NOT EDIT.
// source: keyexchange.proto

package spotify

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Product int32

const (
	Product_PRODUCT_CLIENT              Product = 0
	Product_PRODUCT_LIBSpotify          Product = 1
	Product_PRODUCT_MOBILE              Product = 2
	Product_PRODUCT_PARTNER             Product = 3
	Product_PRODUCT_LIBSpotify_EMBEDDED Product = 5
)

var Product_name = map[int32]string{
	0: "PRODUCT_CLIENT",
	1: "PRODUCT_LIBSpotify",
	2: "PRODUCT_MOBILE",
	3: "PRODUCT_PARTNER",
	5: "PRODUCT_LIBSpotify_EMBEDDED",
}
var Product_value = map[string]int32{
	"PRODUCT_CLIENT":              0,
	"PRODUCT_LIBSpotify":          1,
	"PRODUCT_MOBILE":              2,
	"PRODUCT_PARTNER":             3,
	"PRODUCT_LIBSpotify_EMBEDDED": 5,
}

func (x Product) Enum() *Product {
	p := new(Product)
	*p = x
	return p
}
func (x Product) String() string {
	return proto.EnumName(Product_name, int32(x))
}
func (x *Product) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Product_value, data, "Product")
	if err != nil {
		return err
	}
	*x = Product(value)
	return nil
}
func (Product) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_keyexchange_8d5592f9a470cb57, []int{0}
}

type ProductFlags int32

const (
	ProductFlags_PRODUCT_FLAG_NONE      ProductFlags = 0
	ProductFlags_PRODUCT_FLAG_DEV_BUILD ProductFlags = 1
)

var ProductFlags_name = map[int32]string{
	0: "PRODUCT_FLAG_NONE",
	1: "PRODUCT_FLAG_DEV_BUILD",
}
var ProductFlags_value = map[string]int32{
	"PRODUCT_FLAG_NONE":      0,
	"PRODUCT_FLAG_DEV_BUILD": 1,
}

func (x ProductFlags) Enum() *ProductFlags {
	p := new(ProductFlags)
	*p = x
	return p
}
func (x ProductFlags) String() string {
	return proto.EnumName(ProductFlags_name, int32(x))
}
func (x *ProductFlags) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProductFlags_value, data, "ProductFlags")
	if err != nil {
		return err
	}
	*x = ProductFlags(value)
	return nil
}
func (ProductFlags) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_keyexchange_8d5592f9a470cb57, []int{1}
}

type Platform int32

const (
	Platform_PLATFORM_WIN32_X86      Platform = 0
	Platform_PLATFORM_OSX_X86        Platform = 1
	Platform_PLATFORM_LINUX_X86      Platform = 2
	Platform_PLATFORM_IPHONE_ARM     Platform = 3
	Platform_PLATFORM_S60_ARM        Platform = 4
	Platform_PLATFORM_OSX_PPC        Platform = 5
	Platform_PLATFORM_ANDROID_ARM    Platform = 6
	Platform_PLATFORM_WINDOWS_CE_ARM Platform = 7
	Platform_PLATFORM_LINUX_X86_64   Platform = 8
	Platform_PLATFORM_OSX_X86_64     Platform = 9
	Platform_PLATFORM_PALM_ARM       Platform = 10
	Platform_PLATFORM_LINUX_SH       Platform = 11
	Platform_PLATFORM_FREEBSD_X86    Platform = 12
	Platform_PLATFORM_FREEBSD_X86_64 Platform = 13
	Platform_PLATFORM_BLACKBERRY_ARM Platform = 14
	Platform_PLATFORM_SONOS          Platform = 15
	Platform_PLATFORM_LINUX_MIPS     Platform = 16
	Platform_PLATFORM_LINUX_ARM      Platform = 17
	Platform_PLATFORM_LOGITECH_ARM   Platform = 18
	Platform_PLATFORM_LINUX_BLACKFIN Platform = 19
	Platform_PLATFORM_WP7_ARM        Platform = 20
	Platform_PLATFORM_ONKYO_ARM      Platform = 21
	Platform_PLATFORM_QNXNTO_ARM     Platform = 22
	Platform_PLATFORM_BCO_ARM        Platform = 23
)

var Platform_name = map[int32]string{
	0:  "PLATFORM_WIN32_X86",
	1:  "PLATFORM_OSX_X86",
	2:  "PLATFORM_LINUX_X86",
	3:  "PLATFORM_IPHONE_ARM",
	4:  "PLATFORM_S60_ARM",
	5:  "PLATFORM_OSX_PPC",
	6:  "PLATFORM_ANDROID_ARM",
	7:  "PLATFORM_WINDOWS_CE_ARM",
	8:  "PLATFORM_LINUX_X86_64",
	9:  "PLATFORM_OSX_X86_64",
	10: "PLATFORM_PALM_ARM",
	11: "PLATFORM_LINUX_SH",
	12: "PLATFORM_FREEBSD_X86",
	13: "PLATFORM_FREEBSD_X86_64",
	14: "PLATFORM_BLACKBERRY_ARM",
	15: "PLATFORM_SONOS",
	16: "PLATFORM_LINUX_MIPS",
	17: "PLATFORM_LINUX_ARM",
	18: "PLATFORM_LOGITECH_ARM",
	19: "PLATFORM_LINUX_BLACKFIN",
	20: "PLATFORM_WP7_ARM",
	21: "PLATFORM_ONKYO_ARM",
	22: "PLATFORM_QNXNTO_ARM",
	23: "PLATFORM_BCO_ARM",
}
var Platform_value = map[string]int32{
	"PLATFORM_WIN32_X86":      0,
	"PLATFORM_OSX_X86":        1,
	"PLATFORM_LINUX_X86":      2,
	"PLATFORM_IPHONE_ARM":     3,
	"PLATFORM_S60_ARM":        4,
	"PLATFORM_OSX_PPC":        5,
	"PLATFORM_ANDROID_ARM":    6,
	"PLATFORM_WINDOWS_CE_ARM": 7,
	"PLATFORM_LINUX_X86_64":   8,
	"PLATFORM_OSX_X86_64":     9,
	"PLATFORM_PALM_ARM":       10,
	"PLATFORM_LINUX_SH":       11,
	"PLATFORM_FREEBSD_X86":    12,
	"PLATFORM_FREEBSD_X86_64": 13,
	"PLATFORM_BLACKBERRY_ARM": 14,
	"PLATFORM_SONOS":          15,
	"PLATFORM_LINUX_MIPS":     16,
	"PLATFORM_LINUX_ARM":      17,
	"PLATFORM_LOGITECH_ARM":   18,
	"PLATFORM_LINUX_BLACKFIN": 19,
	"PLATFORM_WP7_ARM":        20,
	"PLATFORM_ONKYO_ARM":      21,
	"PLATFORM_QNXNTO_ARM":     22,
	"PLATFORM_BCO_ARM":        23,
}

func (x Platform) Enum() *Platform {
	p := new(Platform)
	*p = x
	return p
}
func (x Platform) String() string {
	return proto.EnumName(Platform_name, int32(x))
}
func (x *Platform) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Platform_value, data, "Platform")
	if err != nil {
		return err
	}
	*x = Platform(value)
	return nil
}
func (Platform) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_keyexchange_8d5592f9a470cb57, []int{2}
}

type Fingerprint int32

const (
	Fingerprint_FINGERPRINT_GRAIN       Fingerprint = 0
	Fingerprint_FINGERPRINT_HMAC_RIPEMD Fingerprint = 1
)

var Fingerprint_name = map[int32]string{
	0: "FINGERPRINT_GRAIN",
	1: "FINGERPRINT_HMAC_RIPEMD",
}
var Fingerprint_value = map[string]int32{
	"FINGERPRINT_GRAIN":       0,
	"FINGERPRINT_HMAC_RIPEMD": 1,
}

func (x Fingerprint) Enum() *Fingerprint {
	p := new(Fingerprint)
	*p = x
	return p
}
func (x Fingerprint) String() string {
	return proto.EnumName(Fingerprint_name, int32(x))
}
func (x *Fingerprint) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Fingerprint_value, data, "Fingerprint")
	if err != nil {
		return err
	}
	*x = Fingerprint(value)
	return nil
}
func (Fingerprint) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_keyexchange_8d5592f9a470cb57, []int{3}
}

type Cryptosuite int32

const (
	Cryptosuite_CRYPTO_SUITE_SHANNON       Cryptosuite = 0
	Cryptosuite_CRYPTO_SUITE_RC4_SHA1_HMAC Cryptosuite = 1
)

var Cryptosuite_name = map[int32]string{
	0: "CRYPTO_SUITE_SHANNON",
	1: "CRYPTO_SUITE_RC4_SHA1_HMAC",
}
var Cryptosuite_value = map[string]int32{
	"CRYPTO_SUITE_SHANNON":       0,
	"CRYPTO_SUITE_RC4_SHA1_HMAC": 1,
}

func (x Cryptosuite) Enum() *Cryptosuite {
	p := new(Cryptosuite)
	*p = x
	return p
}
func (x Cryptosuite) String() string {
	return proto.EnumName(Cryptosuite_name, int32(x))
}
func (x *Cryptosuite) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Cryptosuite_value, data, "Cryptosuite")
	if err != nil {
		return err
	}
	*x = Cryptosuite(value)
	return nil
}
func (Cryptosuite) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_keyexchange_8d5592f9a470cb57, []int{4}
}

type Powscheme int32

const (
	Powscheme_POW_HASH_CASH Powscheme = 0
)

var Powscheme_name = map[int32]string{
	0: "POW_HASH_CASH",
}
var Powscheme_value = map[string]int32{
	"POW_HASH_CASH": 0,
}

func (x Powscheme) Enum() *Powscheme {
	p := new(Powscheme)
	*p = x
	return p
}
func (x Powscheme) String() string {
	return proto.EnumName(Powscheme_name, int32(x))
}
func (x *Powscheme) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Powscheme_value, data, "Powscheme")
	if err != nil {
		return err
	}
	*x = Powscheme(value)
	return nil
}
func (Powscheme) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_keyexchange_8d5592f9a470cb57, []int{5}
}

type ErrorCode int32

const (
	ErrorCode_ProtocolError               ErrorCode = 0
	ErrorCode_TryAnotherAP                ErrorCode = 2
	ErrorCode_BadConnectionId             ErrorCode = 5
	ErrorCode_TravelRestriction           ErrorCode = 9
	ErrorCode_PremiumAccountRequired      ErrorCode = 11
	ErrorCode_BadCredentials              ErrorCode = 12
	ErrorCode_CouldNotValidateCredentials ErrorCode = 13
	ErrorCode_AccountExists               ErrorCode = 14
	ErrorCode_ExtraVerificationRequired   ErrorCode = 15
	ErrorCode_InvalidAppKey               ErrorCode = 16
	ErrorCode_ApplicationBanned           ErrorCode = 17
)

var ErrorCode_name = map[int32]string{
	0:  "ProtocolError",
	2:  "TryAnotherAP",
	5:  "BadConnectionId",
	9:  "TravelRestriction",
	11: "PremiumAccountRequired",
	12: "BadCredentials",
	13: "CouldNotValidateCredentials",
	14: "AccountExists",
	15: "ExtraVerificationRequired",
	16: "InvalidAppKey",
	17: "ApplicationBanned",
}
var ErrorCode_value = map[string]int32{
	"ProtocolError":               0,
	"TryAnotherAP":                2,
	"BadConnectionId":             5,
	"TravelRestriction":           9,
	"PremiumAccountRequired":      11,
	"BadCredentials":              12,
	"CouldNotValidateCredentials": 13,
	"AccountExists":               14,
	"ExtraVerificationRequired":   15,
	"InvalidAppKey":               16,
	"ApplicationBanned":           17,
}

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}
func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}
func (x *ErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ErrorCode_value, data, "ErrorCode")
	if err != nil {
		return err
	}
	*x = ErrorCode(value)
	return nil
}
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_keyexchange_8d5592f9a470cb57, []int{6}
}

type ClientHello struct {
	BuildInfo             *BuildInfo             `protobuf:"bytes,10,req,name=build_info,json=buildInfo" json:"build_info,omitempty"`
	FingerprintsSupported []Fingerprint          `protobuf:"varint,20,rep,name=fingerprints_supported,json=fingerprintsSupported,enum=spotify.Fingerprint" json:"fingerprints_supported,omitempty"`
	CryptosuitesSupported []Cryptosuite          `protobuf:"varint,30,rep,name=cryptosuites_supported,json=cryptosuitesSupported,enum=spotify.Cryptosuite" json:"cryptosuites_supported,omitempty"`
	PowschemesSupported   []Powscheme            `protobuf:"varint,40,rep,name=powschemes_supported,json=powschemesSupported,enum=spotify.Powscheme" json:"powschemes_supported,omitempty"`
	LoginCryptoHello      *LoginCryptoHelloUnion `protobuf:"bytes,50,req,name=login_crypto_hello,json=loginCryptoHello" json:"login_crypto_hello,omitempty"`
	ClientNonce           []byte                 `protobuf:"bytes,60,req,name=client_nonce,json=clientNonce" json:"client_nonce,omitempty"`
	Padding               []byte                 `protobuf:"bytes,70,opt,name=padding" json:"padding,omitempty"`
	FeatureSet            *FeatureSet            `protobuf:"bytes,80,opt,name=feature_set,json=featureSet" json:"feature_set,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}               `json:"-"`
	XXX_unrecognized      []byte                 `json:"-"`
	XXX_sizecache         int32                  `json:"-"`
}

func (m *ClientHello) Reset()         { *m = ClientHello{} }
func (m *ClientHello) String() string { return proto.CompactTextString(m) }
func (*ClientHello) ProtoMessage()    {}
func (*ClientHello) Descriptor() ([]byte, []int) {
	return fileDescriptor_keyexchange_8d5592f9a470cb57, []int{0}
}
func (m *ClientHello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientHello.Unmarshal(m, b)
}
func (m *ClientHello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientHello.Marshal(b, m, deterministic)
}
func (dst *ClientHello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientHello.Merge(dst, src)
}
func (m *ClientHello) XXX_Size() int {
	return xxx_messageInfo_ClientHello.Size(m)
}
func (m *ClientHello) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientHello.DiscardUnknown(m)
}

var xxx_messageInfo_ClientHello proto.InternalMessageInfo

func (m *ClientHello) GetBuildInfo() *BuildInfo {
	if m != nil {
		return m.BuildInfo
	}
	return nil
}

func (m *ClientHello) GetFingerprintsSupported() []Fingerprint {
	if m != nil {
		return m.FingerprintsSupported
	}
	return nil
}

func (m *ClientHello) GetCryptosuitesSupported() []Cryptosuite {
	if m != nil {
		return m.CryptosuitesSupported
	}
	return nil
}

func (m *ClientHello) GetPowschemesSupported() []Powscheme {
	if m != nil {
		return m.PowschemesSupported
	}
	return nil
}

func (m *ClientHello) GetLoginCryptoHello() *LoginCryptoHelloUnion {
	if m != nil {
		return m.LoginCryptoHello
	}
	return nil
}

func (m *ClientHello) GetClientNonce() []byte {
	if m != nil {
		return m.ClientNonce
	}
	return nil
}

func (m *ClientHello) GetPadding() []byte {
	if m != nil {
		return m.Padding
	}
	return nil
}

func (m *ClientHello) GetFeatureSet() *FeatureSet {
	if m != nil {
		return m.FeatureSet
	}
	return nil
}

type BuildInfo struct {
	Product              *Product       `protobuf:"varint,10,req,name=product,enum=spotify.Product" json:"product,omitempty"`
	ProductFlags         []ProductFlags `protobuf:"varint,20,rep,name=product_flags,json=productFlags,enum=spotify.ProductFlags" json:"product_flags,omitempty"`
	Platform             *Platform      `protobuf:"varint,30,req,name=platform,enum=spotify.Platform" json:"platform,omitempty"`
	Version              *uint64        `protobuf:"varint,40,req,name=version" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BuildInfo) Reset()         { *m = BuildInfo{} }
func (m *BuildInfo) String() string { return proto.CompactTextString(m) }
func (*BuildInfo) ProtoMessage()    {}
func (*BuildInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_keyexchange_8d5592f9a470cb57, []int{1}
}
func (m *BuildInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildInfo.Unmarshal(m, b)
}
func (m *BuildInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildInfo.Marshal(b, m, deterministic)
}
func (dst *BuildInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildInfo.Merge(dst, src)
}
func (m *BuildInfo) XXX_Size() int {
	return xxx_messageInfo_BuildInfo.Size(m)
}
func (m *BuildInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BuildInfo proto.InternalMessageInfo

func (m *BuildInfo) GetProduct() Product {
	if m != nil && m.Product != nil {
		return *m.Product
	}
	return Product_PRODUCT_CLIENT
}

func (m *BuildInfo) GetProductFlags() []ProductFlags {
	if m != nil {
		return m.ProductFlags
	}
	return nil
}

func (m *BuildInfo) GetPlatform() Platform {
	if m != nil && m.Platform != nil {
		return *m.Platform
	}
	return Platform_PLATFORM_WIN32_X86
}

func (m *BuildInfo) GetVersion() uint64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

type LoginCryptoHelloUnion struct {
	DiffieHellman        *LoginCryptoDiffieHellmanHello `protobuf:"bytes,10,opt,name=diffie_hellman,json=diffieHellman" json:"diffie_hellman,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *LoginCryptoHelloUnion) Reset()         { *m = LoginCryptoHelloUnion{} }
func (m *LoginCryptoHelloUnion) String() string { return proto.CompactTextString(m) }
func (*LoginCryptoHelloUnion) ProtoMessage()    {}
func (*LoginCryptoHelloUnion) Descriptor() ([]byte, []int) {
	return fileDescriptor_keyexchange_8d5592f9a470cb57, []int{2}
}
func (m *LoginCryptoHelloUnion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginCryptoHelloUnion.Unmarshal(m, b)
}
func (m *LoginCryptoHelloUnion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginCryptoHelloUnion.Marshal(b, m, deterministic)
}
func (dst *LoginCryptoHelloUnion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginCryptoHelloUnion.Merge(dst, src)
}
func (m *LoginCryptoHelloUnion) XXX_Size() int {
	return xxx_messageInfo_LoginCryptoHelloUnion.Size(m)
}
func (m *LoginCryptoHelloUnion) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginCryptoHelloUnion.DiscardUnknown(m)
}

var xxx_messageInfo_LoginCryptoHelloUnion proto.InternalMessageInfo

func (m *LoginCryptoHelloUnion) GetDiffieHellman() *LoginCryptoDiffieHellmanHello {
	if m != nil {
		return m.DiffieHellman
	}
	return nil
}

type LoginCryptoDiffieHellmanHello struct {
	Gc                   []byte   `protobuf:"bytes,10,req,name=gc" json:"gc,omitempty"`
	ServerKeysKnown      *uint32  `protobuf:"varint,20,req,name=server_keys_known,json=serverKeysKnown" json:"server_keys_known,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginCryptoDiffieHellmanHello) Reset()         { *m = LoginCryptoDiffieHellmanHello{} }
func (m *LoginCryptoDiffieHellmanHello) String() string { return proto.CompactTextString(m) }
func (*LoginCryptoDiffieHellmanHello) ProtoMessage()    {}
func (*LoginCryptoDiffieHellmanHello) Descriptor() ([]byte, []int) {
	return fileDescriptor_keyexchange_8d5592f9a470cb57, []int{3}
}
func (m *LoginCryptoDiffieHellmanHello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginCryptoDiffieHellmanHello.Unmarshal(m, b)
}
func (m *LoginCryptoDiffieHellmanHello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginCryptoDiffieHellmanHello.Marshal(b, m, deterministic)
}
func (dst *LoginCryptoDiffieHellmanHello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginCryptoDiffieHellmanHello.Merge(dst, src)
}
func (m *LoginCryptoDiffieHellmanHello) XXX_Size() int {
	return xxx_messageInfo_LoginCryptoDiffieHellmanHello.Size(m)
}
func (m *LoginCryptoDiffieHellmanHello) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginCryptoDiffieHellmanHello.DiscardUnknown(m)
}

var xxx_messageInfo_LoginCryptoDiffieHellmanHello proto.InternalMessageInfo

func (m *LoginCryptoDiffieHellmanHello) GetGc() []byte {
	if m != nil {
		return m.Gc
	}
	return nil
}

func (m *LoginCryptoDiffieHellmanHello) GetServerKeysKnown() uint32 {
	if m != nil && m.ServerKeysKnown != nil {
		return *m.ServerKeysKnown
	}
	return 0
}

type FeatureSet struct {
	Autoupdate2          *bool    `protobuf:"varint,1,opt,name=autoupdate2" json:"autoupdate2,omitempty"`
	CurrentLocation      *bool    `protobuf:"varint,2,opt,name=current_location,json=currentLocation" json:"current_location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeatureSet) Reset()         { *m = FeatureSet{} }
func (m *FeatureSet) String() string { return proto.CompactTextString(m) }
func (*FeatureSet) ProtoMessage()    {}
func (*FeatureSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_keyexchange_8d5592f9a470cb57, []int{4}
}
func (m *FeatureSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeatureSet.Unmarshal(m, b)
}
func (m *FeatureSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeatureSet.Marshal(b, m, deterministic)
}
func (dst *FeatureSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeatureSet.Merge(dst, src)
}
func (m *FeatureSet) XXX_Size() int {
	return xxx_messageInfo_FeatureSet.Size(m)
}
func (m *FeatureSet) XXX_DiscardUnknown() {
	xxx_messageInfo_FeatureSet.DiscardUnknown(m)
}

var xxx_messageInfo_FeatureSet proto.InternalMessageInfo

func (m *FeatureSet) GetAutoupdate2() bool {
	if m != nil && m.Autoupdate2 != nil {
		return *m.Autoupdate2
	}
	return false
}

func (m *FeatureSet) GetCurrentLocation() bool {
	if m != nil && m.CurrentLocation != nil {
		return *m.CurrentLocation
	}
	return false
}

type APResponseMessage struct {
	Challenge            *APChallenge            `protobuf:"bytes,10,opt,name=challenge" json:"challenge,omitempty"`
	Upgrade              *UpgradeRequiredMessage `protobuf:"bytes,20,opt,name=upgrade" json:"upgrade,omitempty"`
	LoginFailed          *APLoginFailed          `protobuf:"bytes,30,opt,name=login_failed,json=loginFailed" json:"login_failed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *APResponseMessage) Reset()         { *m = APResponseMessage{} }
func (m *APResponseMessage) String() string { return proto.CompactTextString(m) }
func (*APResponseMessage) ProtoMessage()    {}
func (*APResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_keyexchange_8d5592f9a470cb57, []int{5}
}
func (m *APResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APResponseMessage.Unmarshal(m, b)
}
func (m *APResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APResponseMessage.Marshal(b, m, deterministic)
}
func (dst *APResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APResponseMessage.Merge(dst, src)
}
func (m *APResponseMessage) XXX_Size() int {
	return xxx_messageInfo_APResponseMessage.Size(m)
}
func (m *APResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_APResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_APResponseMessage proto.InternalMessageInfo

func (m *APResponseMessage) GetChallenge() *APChallenge {
	if m != nil {
		return m.Challenge
	}
	return nil
}

func (m *APResponseMessage) GetUpgrade() *UpgradeRequiredMessage {
	if m != nil {
		return m.Upgrade
	}
	return nil
}

func (m *APResponseMessage) GetLoginFailed() *APLoginFailed {
	if m != nil {
		return m.LoginFailed
	}
	return nil
}

type APChallenge struct {
	LoginCryptoChallenge *LoginCryptoChallengeUnion `protobuf:"bytes,10,req,name=login_crypto_challenge,json=loginCryptoChallenge" json:"login_crypto_challenge,omitempty"`
	FingerprintChallenge *FingerprintChallengeUnion `protobuf:"bytes,20,req,name=fingerprint_challenge,json=fingerprintChallenge" json:"fingerprint_challenge,omitempty"`
	PowChallenge         *PoWChallengeUnion         `protobuf:"bytes,30,req,name=pow_challenge,json=powChallenge" json:"pow_challenge,omitempty"`
	CryptoChallenge      *CryptoChallengeUnion      `protobuf:"bytes,40,req,name=crypto_challenge,json=cryptoChallenge" json:"crypto_challenge,omitempty"`
	ServerNonce          []byte                     `protobuf:"bytes,50,req,name=server_nonce,json=serverNonce" json:"server_nonce,omitempty"`
	Padding              []byte                     `protobuf:"bytes,60,opt,name=padding" json:"padding,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *APChallenge) Reset()         { *m = APChallenge{} }
func (m *APChallenge) String() string { return proto.CompactTextString(m) }
func (*APChallenge) ProtoMessage()    {}
func (*APChallenge) Descriptor() ([]byte, []int) {
	return fileDescriptor_keyexchange_8d5592f9a470cb57, []int{6}
}
func (m *APChallenge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APChallenge.Unmarshal(m, b)
}
func (m *APChallenge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APChallenge.Marshal(b, m, deterministic)
}
func (dst *APChallenge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APChallenge.Merge(dst, src)
}
func (m *APChallenge) XXX_Size() int {
	return xxx_messageInfo_APChallenge.Size(m)
}
func (m *APChallenge) XXX_DiscardUnknown() {
	xxx_messageInfo_APChallenge.DiscardUnknown(m)
}

var xxx_messageInfo_APChallenge proto.InternalMessageInfo

func (m *APChallenge) GetLoginCryptoChallenge() *LoginCryptoChallengeUnion {
	if m != nil {
		return m.LoginCryptoChallenge
	}
	return nil
}

func (m *APChallenge) GetFingerprintChallenge() *FingerprintChallengeUnion {
	if m != nil {
		return m.FingerprintChallenge
	}
	return nil
}

func (m *APChallenge) GetPowChallenge() *PoWChallengeUnion {
	if m != nil {
		return m.PowChallenge
	}
	return nil
}

func (m *APChallenge) GetCryptoChallenge() *CryptoChallengeUnion {
	if m != nil {
		return m.CryptoChallenge
	}
	return nil
}

func (m *APChallenge) GetServerNonce() []byte {
	if m != nil {
		return m.ServerNonce
	}
	return nil
}

func (m *APChallenge) GetPadding() []byte {
	if m != nil {
		return m.Padding
	}
	return nil
}

type LoginCryptoChallengeUnion struct {
	DiffieHellman        *LoginCryptoDiffieHellmanChallenge `protobuf:"bytes,10,opt,name=diffie_hellman,json=diffieHellman" json:"diffie_hellman,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *LoginCryptoChallengeUnion) Reset()         { *m = LoginCryptoChallengeUnion{} }
func (m *LoginCryptoChallengeUnion) String() string { return proto.CompactTextString(m) }
func (*LoginCryptoChallengeUnion) ProtoMessage()    {}
func (*LoginCryptoChallengeUnion) Descriptor() ([]byte, []int) {
	return fileDescriptor_keyexchange_8d5592f9a470cb57, []int{7}
}
func (m *LoginCryptoChallengeUnion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginCryptoChallengeUnion.Unmarshal(m, b)
}
func (m *LoginCryptoChallengeUnion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginCryptoChallengeUnion.Marshal(b, m, deterministic)
}
func (dst *LoginCryptoChallengeUnion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginCryptoChallengeUnion.Merge(dst, src)
}
func (m *LoginCryptoChallengeUnion) XXX_Size() int {
	return xxx_messageInfo_LoginCryptoChallengeUnion.Size(m)
}
func (m *LoginCryptoChallengeUnion) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginCryptoChallengeUnion.DiscardUnknown(m)
}

var xxx_messageInfo_LoginCryptoChallengeUnion proto.InternalMessageInfo

func (m *LoginCryptoChallengeUnion) GetDiffieHellman() *LoginCryptoDiffieHellmanChallenge {
	if m != nil {
		return m.DiffieHellman
	}
	return nil
}

type LoginCryptoDiffieHellmanChallenge struct {
	Gs                   []byte   `protobuf:"bytes,10,req,name=gs" json:"gs,omitempty"`
	ServerSignatureKey   *int32   `protobuf:"varint,20,req,name=server_signature_key,json=serverSignatureKey" json:"server_signature_key,omitempty"`
	GsSignature          []byte   `protobuf:"bytes,30,req,name=gs_signature,json=gsSignature" json:"gs_signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginCryptoDiffieHellmanChallenge) Reset()         { *m = LoginCryptoDiffieHellmanChallenge{} }
func (m *LoginCryptoDiffieHellmanChallenge) String() string { return proto.CompactTextString(m) }
func (*LoginCryptoDiffieHellmanChallenge) ProtoMessage()    {}
func (*LoginCryptoDiffieHellmanChallenge) Descriptor() ([]byte, []int) {
	return fileDescriptor_keyexchange_8d5592f9a470cb57, []int{8}
}
func (m *LoginCryptoDiffieHellmanChallenge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginCryptoDiffieHellmanChallenge.Unmarshal(m, b)
}
func (m *LoginCryptoDiffieHellmanChallenge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginCryptoDiffieHellmanChallenge.Marshal(b, m, deterministic)
}
func (dst *LoginCryptoDiffieHellmanChallenge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginCryptoDiffieHellmanChallenge.Merge(dst, src)
}
func (m *LoginCryptoDiffieHellmanChallenge) XXX_Size() int {
	return xxx_messageInfo_LoginCryptoDiffieHellmanChallenge.Size(m)
}
func (m *LoginCryptoDiffieHellmanChallenge) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginCryptoDiffieHellmanChallenge.DiscardUnknown(m)
}

var xxx_messageInfo_LoginCryptoDiffieHellmanChallenge proto.InternalMessageInfo

func (m *LoginCryptoDiffieHellmanChallenge) GetGs() []byte {
	if m != nil {
		return m.Gs
	}
	return nil
}

func (m *LoginCryptoDiffieHellmanChallenge) GetServerSignatureKey() int32 {
	if m != nil && m.ServerSignatureKey != nil {
		return *m.ServerSignatureKey
	}
	return 0
}

func (m *LoginCryptoDiffieHellmanChallenge) GetGsSignature() []byte {
	if m != nil {
		return m.GsSignature
	}
	return nil
}

type FingerprintChallengeUnion struct {
	Grain                *FingerprintGrainChallenge      `protobuf:"bytes,10,opt,name=grain" json:"grain,omitempty"`
	HmacRipemd           *FingerprintHmacRipemdChallenge `protobuf:"bytes,20,opt,name=hmac_ripemd,json=hmacRipemd" json:"hmac_ripemd,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *FingerprintChallengeUnion) Reset()         { *m = FingerprintChallengeUnion{} }
func (m *FingerprintChallengeUnion) String() string { return proto.CompactTextString(m) }
func (*FingerprintChallengeUnion) ProtoMessage()    {}
func (*FingerprintChallengeUnion) Descriptor() ([]byte, []int) {
	return fileDescriptor_keyexchange_8d5592f9a470cb57, []int{9}
}
func (m *FingerprintChallengeUnion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FingerprintChallengeUnion.Unmarshal(m, b)
}
func (m *FingerprintChallengeUnion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FingerprintChallengeUnion.Marshal(b, m, deterministic)
}
func (dst *FingerprintChallengeUnion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FingerprintChallengeUnion.Merge(dst, src)
}
func (m *FingerprintChallengeUnion) XXX_Size() int {
	return xxx_messageInfo_FingerprintChallengeUnion.Size(m)
}
func (m *FingerprintChallengeUnion) XXX_DiscardUnknown() {
	xxx_messageInfo_FingerprintChallengeUnion.DiscardUnknown(m)
}

var xxx_messageInfo_FingerprintChallengeUnion proto.InternalMessageInfo

func (m *FingerprintChallengeUnion) GetGrain() *FingerprintGrainChallenge {
	if m != nil {
		return m.Grain
	}
	return nil
}

func (m *FingerprintChallengeUnion) GetHmacRipemd() *FingerprintHmacRipemdChallenge {
	if m != nil {
		return m.HmacRipemd
	}
	return nil
}

type FingerprintGrainChallenge struct {
	Kek                  []byte   `protobuf:"bytes,10,req,name=kek" json:"kek,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FingerprintGrainChallenge) Reset()         { *m = FingerprintGrainChallenge{} }
func (m *FingerprintGrainChallenge) String() string { return proto.CompactTextString(m) }
func (*FingerprintGrainChallenge) ProtoMessage()    {}
func (*FingerprintGrainChallenge) Descriptor() ([]byte, []int) {
	return fileDescriptor_keyexchange_8d5592f9a470cb57, []int{10}
}
func (m *FingerprintGrainChallenge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FingerprintGrainChallenge.Unmarshal(m, b)
}
func (m *FingerprintGrainChallenge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FingerprintGrainChallenge.Marshal(b, m, deterministic)
}
func (dst *FingerprintGrainChallenge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FingerprintGrainChallenge.Merge(dst, src)
}
func (m *FingerprintGrainChallenge) XXX_Size() int {
	return xxx_messageInfo_FingerprintGrainChallenge.Size(m)
}
func (m *FingerprintGrainChallenge) XXX_DiscardUnknown() {
	xxx_messageInfo_FingerprintGrainChallenge.DiscardUnknown(m)
}

var xxx_messageInfo_FingerprintGrainChallenge proto.InternalMessageInfo

func (m *FingerprintGrainChallenge) GetKek() []byte {
	if m != nil {
		return m.Kek
	}
	return nil
}

type FingerprintHmacRipemdChallenge struct {
	Challenge            []byte   `protobuf:"bytes,10,req,name=challenge" json:"challenge,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FingerprintHmacRipemdChallenge) Reset()         { *m = FingerprintHmacRipemdChallenge{} }
func (m *FingerprintHmacRipemdChallenge) String() string { return proto.CompactTextString(m) }
func (*FingerprintHmacRipemdChallenge) ProtoMessage()    {}
func (*FingerprintHmacRipemdChallenge) Descriptor() ([]byte, []int) {
	return fileDescriptor_keyexchange_8d5592f9a470cb57, []int{11}
}
func (m *FingerprintHmacRipemdChallenge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FingerprintHmacRipemdChallenge.Unmarshal(m, b)
}
func (m *FingerprintHmacRipemdChallenge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FingerprintHmacRipemdChallenge.Marshal(b, m, deterministic)
}
func (dst *FingerprintHmacRipemdChallenge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FingerprintHmacRipemdChallenge.Merge(dst, src)
}
func (m *FingerprintHmacRipemdChallenge) XXX_Size() int {
	return xxx_messageInfo_FingerprintHmacRipemdChallenge.Size(m)
}
func (m *FingerprintHmacRipemdChallenge) XXX_DiscardUnknown() {
	xxx_messageInfo_FingerprintHmacRipemdChallenge.DiscardUnknown(m)
}

var xxx_messageInfo_FingerprintHmacRipemdChallenge proto.InternalMessageInfo

func (m *FingerprintHmacRipemdChallenge) GetChallenge() []byte {
	if m != nil {
		return m.Challenge
	}
	return nil
}

type PoWChallengeUnion struct {
	HashCash             *PoWHashCashChallenge `protobuf:"bytes,10,opt,name=hash_cash,json=hashCash" json:"hash_cash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *PoWChallengeUnion) Reset()         { *m = PoWChallengeUnion{} }
func (m *PoWChallengeUnion) String() string { return proto.CompactTextString(m) }
func (*PoWChallengeUnion) ProtoMessage()    {}
func (*PoWChallengeUnion) Descriptor() ([]byte, []int) {
	return fileDescriptor_keyexchange_8d5592f9a470cb57, []int{12}
}
func (m *PoWChallengeUnion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PoWChallengeUnion.Unmarshal(m, b)
}
func (m *PoWChallengeUnion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PoWChallengeUnion.Marshal(b, m, deterministic)
}
func (dst *PoWChallengeUnion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoWChallengeUnion.Merge(dst, src)
}
func (m *PoWChallengeUnion) XXX_Size() int {
	return xxx_messageInfo_PoWChallengeUnion.Size(m)
}
func (m *PoWChallengeUnion) XXX_DiscardUnknown() {
	xxx_messageInfo_PoWChallengeUnion.DiscardUnknown(m)
}

var xxx_messageInfo_PoWChallengeUnion proto.InternalMessageInfo

func (m *PoWChallengeUnion) GetHashCash() *PoWHashCashChallenge {
	if m != nil {
		return m.HashCash
	}
	return nil
}

type PoWHashCashChallenge struct {
	Prefix               []byte   `protobuf:"bytes,10,opt,name=prefix" json:"prefix,omitempty"`
	Length               *int32   `protobuf:"varint,20,opt,name=length" json:"length,omitempty"`
	Target               *int32   `protobuf:"varint,30,opt,name=target" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PoWHashCashChallenge) Reset()         { *m = PoWHashCashChallenge{} }
func (m *PoWHashCashChallenge) String() string { return proto.CompactTextString(m) }
func (*PoWHashCashChallenge) ProtoMessage()    {}
func (*PoWHashCashChallenge) Descriptor() ([]byte, []int) {
	return fileDescriptor_keyexchange_8d5592f9a470cb57, []int{13}
}
func (m *PoWHashCashChallenge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PoWHashCashChallenge.Unmarshal(m, b)
}
func (m *PoWHashCashChallenge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PoWHashCashChallenge.Marshal(b, m, deterministic)
}
func (dst *PoWHashCashChallenge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoWHashCashChallenge.Merge(dst, src)
}
func (m *PoWHashCashChallenge) XXX_Size() int {
	return xxx_messageInfo_PoWHashCashChallenge.Size(m)
}
func (m *PoWHashCashChallenge) XXX_DiscardUnknown() {
	xxx_messageInfo_PoWHashCashChallenge.DiscardUnknown(m)
}

var xxx_messageInfo_PoWHashCashChallenge proto.InternalMessageInfo

func (m *PoWHashCashChallenge) GetPrefix() []byte {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *PoWHashCashChallenge) GetLength() int32 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *PoWHashCashChallenge) GetTarget() int32 {
	if m != nil && m.Target != nil {
		return *m.Target
	}
	return 0
}

type CryptoChallengeUnion struct {
	Shannon              *CryptoShannonChallenge     `protobuf:"bytes,10,opt,name=shannon" json:"shannon,omitempty"`
	Rc4Sha1Hmac          *CryptoRc4Sha1HmacChallenge `protobuf:"bytes,20,opt,name=rc4_sha1_hmac,json=rc4Sha1Hmac" json:"rc4_sha1_hmac,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *CryptoChallengeUnion) Reset()         { *m = CryptoChallengeUnion{} }
func (m *CryptoChallengeUnion) String() string { return proto.CompactTextString(m) }
func (*CryptoChallengeUnion) ProtoMessage()    {}
func (*CryptoChallengeUnion) Descriptor() ([]byte, []int) {
	return fileDescriptor_keyexchange_8d5592f9a470cb57, []int{14}
}
func (m *CryptoChallengeUnion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CryptoChallengeUnion.Unmarshal(m, b)
}
func (m *CryptoChallengeUnion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CryptoChallengeUnion.Marshal(b, m, deterministic)
}
func (dst *CryptoChallengeUnion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CryptoChallengeUnion.Merge(dst, src)
}
func (m *CryptoChallengeUnion) XXX_Size() int {
	return xxx_messageInfo_CryptoChallengeUnion.Size(m)
}
func (m *CryptoChallengeUnion) XXX_DiscardUnknown() {
	xxx_messageInfo_CryptoChallengeUnion.DiscardUnknown(m)
}

var xxx_messageInfo_CryptoChallengeUnion proto.InternalMessageInfo

func (m *CryptoChallengeUnion) GetShannon() *CryptoShannonChallenge {
	if m != nil {
		return m.Shannon
	}
	return nil
}

func (m *CryptoChallengeUnion) GetRc4Sha1Hmac() *CryptoRc4Sha1HmacChallenge {
	if m != nil {
		return m.Rc4Sha1Hmac
	}
	return nil
}

type CryptoShannonChallenge struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CryptoShannonChallenge) Reset()         { *m = CryptoShannonChallenge{} }
func (m *CryptoShannonChallenge) String() string { return proto.CompactTextString(m) }
func (*CryptoShannonChallenge) ProtoMessage()    {}
func (*CryptoShannonChallenge) Descriptor() ([]byte, []int) {
	return fileDescriptor_keyexchange_8d5592f9a470cb57, []int{15}
}
func (m *CryptoShannonChallenge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CryptoShannonChallenge.Unmarshal(m, b)
}
func (m *CryptoShannonChallenge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CryptoShannonChallenge.Marshal(b, m, deterministic)
}
func (dst *CryptoShannonChallenge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CryptoShannonChallenge.Merge(dst, src)
}
func (m *CryptoShannonChallenge) XXX_Size() int {
	return xxx_messageInfo_CryptoShannonChallenge.Size(m)
}
func (m *CryptoShannonChallenge) XXX_DiscardUnknown() {
	xxx_messageInfo_CryptoShannonChallenge.DiscardUnknown(m)
}

var xxx_messageInfo_CryptoShannonChallenge proto.InternalMessageInfo

type CryptoRc4Sha1HmacChallenge struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CryptoRc4Sha1HmacChallenge) Reset()         { *m = CryptoRc4Sha1HmacChallenge{} }
func (m *CryptoRc4Sha1HmacChallenge) String() string { return proto.CompactTextString(m) }
func (*CryptoRc4Sha1HmacChallenge) ProtoMessage()    {}
func (*CryptoRc4Sha1HmacChallenge) Descriptor() ([]byte, []int) {
	return fileDescriptor_keyexchange_8d5592f9a470cb57, []int{16}
}
func (m *CryptoRc4Sha1HmacChallenge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CryptoRc4Sha1HmacChallenge.Unmarshal(m, b)
}
func (m *CryptoRc4Sha1HmacChallenge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CryptoRc4Sha1HmacChallenge.Marshal(b, m, deterministic)
}
func (dst *CryptoRc4Sha1HmacChallenge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CryptoRc4Sha1HmacChallenge.Merge(dst, src)
}
func (m *CryptoRc4Sha1HmacChallenge) XXX_Size() int {
	return xxx_messageInfo_CryptoRc4Sha1HmacChallenge.Size(m)
}
func (m *CryptoRc4Sha1HmacChallenge) XXX_DiscardUnknown() {
	xxx_messageInfo_CryptoRc4Sha1HmacChallenge.DiscardUnknown(m)
}

var xxx_messageInfo_CryptoRc4Sha1HmacChallenge proto.InternalMessageInfo

type UpgradeRequiredMessage struct {
	UpgradeSignedPart    []byte   `protobuf:"bytes,10,req,name=upgrade_signed_part,json=upgradeSignedPart" json:"upgrade_signed_part,omitempty"`
	Signature            []byte   `protobuf:"bytes,20,req,name=signature" json:"signature,omitempty"`
	HttpSuffix           *string  `protobuf:"bytes,30,opt,name=http_suffix,json=httpSuffix" json:"http_suffix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpgradeRequiredMessage) Reset()         { *m = UpgradeRequiredMessage{} }
func (m *UpgradeRequiredMessage) String() string { return proto.CompactTextString(m) }
func (*UpgradeRequiredMessage) ProtoMessage()    {}
func (*UpgradeRequiredMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_keyexchange_8d5592f9a470cb57, []int{17}
}
func (m *UpgradeRequiredMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeRequiredMessage.Unmarshal(m, b)
}
func (m *UpgradeRequiredMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeRequiredMessage.Marshal(b, m, deterministic)
}
func (dst *UpgradeRequiredMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeRequiredMessage.Merge(dst, src)
}
func (m *UpgradeRequiredMessage) XXX_Size() int {
	return xxx_messageInfo_UpgradeRequiredMessage.Size(m)
}
func (m *UpgradeRequiredMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeRequiredMessage.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeRequiredMessage proto.InternalMessageInfo

func (m *UpgradeRequiredMessage) GetUpgradeSignedPart() []byte {
	if m != nil {
		return m.UpgradeSignedPart
	}
	return nil
}

func (m *UpgradeRequiredMessage) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *UpgradeRequiredMessage) GetHttpSuffix() string {
	if m != nil && m.HttpSuffix != nil {
		return *m.HttpSuffix
	}
	return ""
}

type APLoginFailed struct {
	ErrorCode            *ErrorCode `protobuf:"varint,10,req,name=error_code,json=errorCode,enum=spotify.ErrorCode" json:"error_code,omitempty"`
	RetryDelay           *int32     `protobuf:"varint,20,opt,name=retry_delay,json=retryDelay" json:"retry_delay,omitempty"`
	Expiry               *int32     `protobuf:"varint,30,opt,name=expiry" json:"expiry,omitempty"`
	ErrorDescription     *string    `protobuf:"bytes,40,opt,name=error_description,json=errorDescription" json:"error_description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *APLoginFailed) Reset()         { *m = APLoginFailed{} }
func (m *APLoginFailed) String() string { return proto.CompactTextString(m) }
func (*APLoginFailed) ProtoMessage()    {}
func (*APLoginFailed) Descriptor() ([]byte, []int) {
	return fileDescriptor_keyexchange_8d5592f9a470cb57, []int{18}
}
func (m *APLoginFailed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APLoginFailed.Unmarshal(m, b)
}
func (m *APLoginFailed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APLoginFailed.Marshal(b, m, deterministic)
}
func (dst *APLoginFailed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APLoginFailed.Merge(dst, src)
}
func (m *APLoginFailed) XXX_Size() int {
	return xxx_messageInfo_APLoginFailed.Size(m)
}
func (m *APLoginFailed) XXX_DiscardUnknown() {
	xxx_messageInfo_APLoginFailed.DiscardUnknown(m)
}

var xxx_messageInfo_APLoginFailed proto.InternalMessageInfo

func (m *APLoginFailed) GetErrorCode() ErrorCode {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return ErrorCode_ProtocolError
}

func (m *APLoginFailed) GetRetryDelay() int32 {
	if m != nil && m.RetryDelay != nil {
		return *m.RetryDelay
	}
	return 0
}

func (m *APLoginFailed) GetExpiry() int32 {
	if m != nil && m.Expiry != nil {
		return *m.Expiry
	}
	return 0
}

func (m *APLoginFailed) GetErrorDescription() string {
	if m != nil && m.ErrorDescription != nil {
		return *m.ErrorDescription
	}
	return ""
}

type ClientResponsePlaintext struct {
	LoginCryptoResponse  *LoginCryptoResponseUnion `protobuf:"bytes,10,req,name=login_crypto_response,json=loginCryptoResponse" json:"login_crypto_response,omitempty"`
	PowResponse          *PoWResponseUnion         `protobuf:"bytes,20,req,name=pow_response,json=powResponse" json:"pow_response,omitempty"`
	CryptoResponse       *CryptoResponseUnion      `protobuf:"bytes,30,req,name=crypto_response,json=cryptoResponse" json:"crypto_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ClientResponsePlaintext) Reset()         { *m = ClientResponsePlaintext{} }
func (m *ClientResponsePlaintext) String() string { return proto.CompactTextString(m) }
func (*ClientResponsePlaintext) ProtoMessage()    {}
func (*ClientResponsePlaintext) Descriptor() ([]byte, []int) {
	return fileDescriptor_keyexchange_8d5592f9a470cb57, []int{19}
}
func (m *ClientResponsePlaintext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientResponsePlaintext.Unmarshal(m, b)
}
func (m *ClientResponsePlaintext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientResponsePlaintext.Marshal(b, m, deterministic)
}
func (dst *ClientResponsePlaintext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientResponsePlaintext.Merge(dst, src)
}
func (m *ClientResponsePlaintext) XXX_Size() int {
	return xxx_messageInfo_ClientResponsePlaintext.Size(m)
}
func (m *ClientResponsePlaintext) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientResponsePlaintext.DiscardUnknown(m)
}

var xxx_messageInfo_ClientResponsePlaintext proto.InternalMessageInfo

func (m *ClientResponsePlaintext) GetLoginCryptoResponse() *LoginCryptoResponseUnion {
	if m != nil {
		return m.LoginCryptoResponse
	}
	return nil
}

func (m *ClientResponsePlaintext) GetPowResponse() *PoWResponseUnion {
	if m != nil {
		return m.PowResponse
	}
	return nil
}

func (m *ClientResponsePlaintext) GetCryptoResponse() *CryptoResponseUnion {
	if m != nil {
		return m.CryptoResponse
	}
	return nil
}

type LoginCryptoResponseUnion struct {
	DiffieHellman        *LoginCryptoDiffieHellmanResponse `protobuf:"bytes,10,opt,name=diffie_hellman,json=diffieHellman" json:"diffie_hellman,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *LoginCryptoResponseUnion) Reset()         { *m = LoginCryptoResponseUnion{} }
func (m *LoginCryptoResponseUnion) String() string { return proto.CompactTextString(m) }
func (*LoginCryptoResponseUnion) ProtoMessage()    {}
func (*LoginCryptoResponseUnion) Descriptor() ([]byte, []int) {
	return fileDescriptor_keyexchange_8d5592f9a470cb57, []int{20}
}
func (m *LoginCryptoResponseUnion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginCryptoResponseUnion.Unmarshal(m, b)
}
func (m *LoginCryptoResponseUnion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginCryptoResponseUnion.Marshal(b, m, deterministic)
}
func (dst *LoginCryptoResponseUnion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginCryptoResponseUnion.Merge(dst, src)
}
func (m *LoginCryptoResponseUnion) XXX_Size() int {
	return xxx_messageInfo_LoginCryptoResponseUnion.Size(m)
}
func (m *LoginCryptoResponseUnion) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginCryptoResponseUnion.DiscardUnknown(m)
}

var xxx_messageInfo_LoginCryptoResponseUnion proto.InternalMessageInfo

func (m *LoginCryptoResponseUnion) GetDiffieHellman() *LoginCryptoDiffieHellmanResponse {
	if m != nil {
		return m.DiffieHellman
	}
	return nil
}

type LoginCryptoDiffieHellmanResponse struct {
	Hmac                 []byte   `protobuf:"bytes,10,req,name=hmac" json:"hmac,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginCryptoDiffieHellmanResponse) Reset()         { *m = LoginCryptoDiffieHellmanResponse{} }
func (m *LoginCryptoDiffieHellmanResponse) String() string { return proto.CompactTextString(m) }
func (*LoginCryptoDiffieHellmanResponse) ProtoMessage()    {}
func (*LoginCryptoDiffieHellmanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_keyexchange_8d5592f9a470cb57, []int{21}
}
func (m *LoginCryptoDiffieHellmanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginCryptoDiffieHellmanResponse.Unmarshal(m, b)
}
func (m *LoginCryptoDiffieHellmanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginCryptoDiffieHellmanResponse.Marshal(b, m, deterministic)
}
func (dst *LoginCryptoDiffieHellmanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginCryptoDiffieHellmanResponse.Merge(dst, src)
}
func (m *LoginCryptoDiffieHellmanResponse) XXX_Size() int {
	return xxx_messageInfo_LoginCryptoDiffieHellmanResponse.Size(m)
}
func (m *LoginCryptoDiffieHellmanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginCryptoDiffieHellmanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginCryptoDiffieHellmanResponse proto.InternalMessageInfo

func (m *LoginCryptoDiffieHellmanResponse) GetHmac() []byte {
	if m != nil {
		return m.Hmac
	}
	return nil
}

type PoWResponseUnion struct {
	HashCash             *PoWHashCashResponse `protobuf:"bytes,10,opt,name=hash_cash,json=hashCash" json:"hash_cash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PoWResponseUnion) Reset()         { *m = PoWResponseUnion{} }
func (m *PoWResponseUnion) String() string { return proto.CompactTextString(m) }
func (*PoWResponseUnion) ProtoMessage()    {}
func (*PoWResponseUnion) Descriptor() ([]byte, []int) {
	return fileDescriptor_keyexchange_8d5592f9a470cb57, []int{22}
}
func (m *PoWResponseUnion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PoWResponseUnion.Unmarshal(m, b)
}
func (m *PoWResponseUnion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PoWResponseUnion.Marshal(b, m, deterministic)
}
func (dst *PoWResponseUnion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoWResponseUnion.Merge(dst, src)
}
func (m *PoWResponseUnion) XXX_Size() int {
	return xxx_messageInfo_PoWResponseUnion.Size(m)
}
func (m *PoWResponseUnion) XXX_DiscardUnknown() {
	xxx_messageInfo_PoWResponseUnion.DiscardUnknown(m)
}

var xxx_messageInfo_PoWResponseUnion proto.InternalMessageInfo

func (m *PoWResponseUnion) GetHashCash() *PoWHashCashResponse {
	if m != nil {
		return m.HashCash
	}
	return nil
}

type PoWHashCashResponse struct {
	HashSuffix           []byte   `protobuf:"bytes,10,req,name=hash_suffix,json=hashSuffix" json:"hash_suffix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PoWHashCashResponse) Reset()         { *m = PoWHashCashResponse{} }
func (m *PoWHashCashResponse) String() string { return proto.CompactTextString(m) }
func (*PoWHashCashResponse) ProtoMessage()    {}
func (*PoWHashCashResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_keyexchange_8d5592f9a470cb57, []int{23}
}
func (m *PoWHashCashResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PoWHashCashResponse.Unmarshal(m, b)
}
func (m *PoWHashCashResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PoWHashCashResponse.Marshal(b, m, deterministic)
}
func (dst *PoWHashCashResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoWHashCashResponse.Merge(dst, src)
}
func (m *PoWHashCashResponse) XXX_Size() int {
	return xxx_messageInfo_PoWHashCashResponse.Size(m)
}
func (m *PoWHashCashResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PoWHashCashResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PoWHashCashResponse proto.InternalMessageInfo

func (m *PoWHashCashResponse) GetHashSuffix() []byte {
	if m != nil {
		return m.HashSuffix
	}
	return nil
}

type CryptoResponseUnion struct {
	Shannon              *CryptoShannonResponse     `protobuf:"bytes,10,opt,name=shannon" json:"shannon,omitempty"`
	Rc4Sha1Hmac          *CryptoRc4Sha1HmacResponse `protobuf:"bytes,20,opt,name=rc4_sha1_hmac,json=rc4Sha1Hmac" json:"rc4_sha1_hmac,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CryptoResponseUnion) Reset()         { *m = CryptoResponseUnion{} }
func (m *CryptoResponseUnion) String() string { return proto.CompactTextString(m) }
func (*CryptoResponseUnion) ProtoMessage()    {}
func (*CryptoResponseUnion) Descriptor() ([]byte, []int) {
	return fileDescriptor_keyexchange_8d5592f9a470cb57, []int{24}
}
func (m *CryptoResponseUnion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CryptoResponseUnion.Unmarshal(m, b)
}
func (m *CryptoResponseUnion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CryptoResponseUnion.Marshal(b, m, deterministic)
}
func (dst *CryptoResponseUnion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CryptoResponseUnion.Merge(dst, src)
}
func (m *CryptoResponseUnion) XXX_Size() int {
	return xxx_messageInfo_CryptoResponseUnion.Size(m)
}
func (m *CryptoResponseUnion) XXX_DiscardUnknown() {
	xxx_messageInfo_CryptoResponseUnion.DiscardUnknown(m)
}

var xxx_messageInfo_CryptoResponseUnion proto.InternalMessageInfo

func (m *CryptoResponseUnion) GetShannon() *CryptoShannonResponse {
	if m != nil {
		return m.Shannon
	}
	return nil
}

func (m *CryptoResponseUnion) GetRc4Sha1Hmac() *CryptoRc4Sha1HmacResponse {
	if m != nil {
		return m.Rc4Sha1Hmac
	}
	return nil
}

type CryptoShannonResponse struct {
	Dummy                *int32   `protobuf:"varint,1,opt,name=dummy" json:"dummy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CryptoShannonResponse) Reset()         { *m = CryptoShannonResponse{} }
func (m *CryptoShannonResponse) String() string { return proto.CompactTextString(m) }
func (*CryptoShannonResponse) ProtoMessage()    {}
func (*CryptoShannonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_keyexchange_8d5592f9a470cb57, []int{25}
}
func (m *CryptoShannonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CryptoShannonResponse.Unmarshal(m, b)
}
func (m *CryptoShannonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CryptoShannonResponse.Marshal(b, m, deterministic)
}
func (dst *CryptoShannonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CryptoShannonResponse.Merge(dst, src)
}
func (m *CryptoShannonResponse) XXX_Size() int {
	return xxx_messageInfo_CryptoShannonResponse.Size(m)
}
func (m *CryptoShannonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CryptoShannonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CryptoShannonResponse proto.InternalMessageInfo

func (m *CryptoShannonResponse) GetDummy() int32 {
	if m != nil && m.Dummy != nil {
		return *m.Dummy
	}
	return 0
}

type CryptoRc4Sha1HmacResponse struct {
	Dummy                *int32   `protobuf:"varint,1,opt,name=dummy" json:"dummy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CryptoRc4Sha1HmacResponse) Reset()         { *m = CryptoRc4Sha1HmacResponse{} }
func (m *CryptoRc4Sha1HmacResponse) String() string { return proto.CompactTextString(m) }
func (*CryptoRc4Sha1HmacResponse) ProtoMessage()    {}
func (*CryptoRc4Sha1HmacResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_keyexchange_8d5592f9a470cb57, []int{26}
}
func (m *CryptoRc4Sha1HmacResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CryptoRc4Sha1HmacResponse.Unmarshal(m, b)
}
func (m *CryptoRc4Sha1HmacResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CryptoRc4Sha1HmacResponse.Marshal(b, m, deterministic)
}
func (dst *CryptoRc4Sha1HmacResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CryptoRc4Sha1HmacResponse.Merge(dst, src)
}
func (m *CryptoRc4Sha1HmacResponse) XXX_Size() int {
	return xxx_messageInfo_CryptoRc4Sha1HmacResponse.Size(m)
}
func (m *CryptoRc4Sha1HmacResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CryptoRc4Sha1HmacResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CryptoRc4Sha1HmacResponse proto.InternalMessageInfo

func (m *CryptoRc4Sha1HmacResponse) GetDummy() int32 {
	if m != nil && m.Dummy != nil {
		return *m.Dummy
	}
	return 0
}

func init() {
	proto.RegisterType((*ClientHello)(nil), "spotify.ClientHello")
	proto.RegisterType((*BuildInfo)(nil), "spotify.BuildInfo")
	proto.RegisterType((*LoginCryptoHelloUnion)(nil), "spotify.LoginCryptoHelloUnion")
	proto.RegisterType((*LoginCryptoDiffieHellmanHello)(nil), "spotify.LoginCryptoDiffieHellmanHello")
	proto.RegisterType((*FeatureSet)(nil), "spotify.FeatureSet")
	proto.RegisterType((*APResponseMessage)(nil), "spotify.APResponseMessage")
	proto.RegisterType((*APChallenge)(nil), "spotify.APChallenge")
	proto.RegisterType((*LoginCryptoChallengeUnion)(nil), "spotify.LoginCryptoChallengeUnion")
	proto.RegisterType((*LoginCryptoDiffieHellmanChallenge)(nil), "spotify.LoginCryptoDiffieHellmanChallenge")
	proto.RegisterType((*FingerprintChallengeUnion)(nil), "spotify.FingerprintChallengeUnion")
	proto.RegisterType((*FingerprintGrainChallenge)(nil), "spotify.FingerprintGrainChallenge")
	proto.RegisterType((*FingerprintHmacRipemdChallenge)(nil), "spotify.FingerprintHmacRipemdChallenge")
	proto.RegisterType((*PoWChallengeUnion)(nil), "spotify.PoWChallengeUnion")
	proto.RegisterType((*PoWHashCashChallenge)(nil), "spotify.PoWHashCashChallenge")
	proto.RegisterType((*CryptoChallengeUnion)(nil), "spotify.CryptoChallengeUnion")
	proto.RegisterType((*CryptoShannonChallenge)(nil), "spotify.CryptoShannonChallenge")
	proto.RegisterType((*CryptoRc4Sha1HmacChallenge)(nil), "spotify.CryptoRc4Sha1HmacChallenge")
	proto.RegisterType((*UpgradeRequiredMessage)(nil), "spotify.UpgradeRequiredMessage")
	proto.RegisterType((*APLoginFailed)(nil), "spotify.APLoginFailed")
	proto.RegisterType((*ClientResponsePlaintext)(nil), "spotify.ClientResponsePlaintext")
	proto.RegisterType((*LoginCryptoResponseUnion)(nil), "spotify.LoginCryptoResponseUnion")
	proto.RegisterType((*LoginCryptoDiffieHellmanResponse)(nil), "spotify.LoginCryptoDiffieHellmanResponse")
	proto.RegisterType((*PoWResponseUnion)(nil), "spotify.PoWResponseUnion")
	proto.RegisterType((*PoWHashCashResponse)(nil), "spotify.PoWHashCashResponse")
	proto.RegisterType((*CryptoResponseUnion)(nil), "spotify.CryptoResponseUnion")
	proto.RegisterType((*CryptoShannonResponse)(nil), "spotify.CryptoShannonResponse")
	proto.RegisterType((*CryptoRc4Sha1HmacResponse)(nil), "spotify.CryptoRc4Sha1HmacResponse")
	proto.RegisterEnum("spotify.Product", Product_name, Product_value)
	proto.RegisterEnum("spotify.ProductFlags", ProductFlags_name, ProductFlags_value)
	proto.RegisterEnum("spotify.Platform", Platform_name, Platform_value)
	proto.RegisterEnum("spotify.Fingerprint", Fingerprint_name, Fingerprint_value)
	proto.RegisterEnum("spotify.Cryptosuite", Cryptosuite_name, Cryptosuite_value)
	proto.RegisterEnum("spotify.Powscheme", Powscheme_name, Powscheme_value)
	proto.RegisterEnum("spotify.ErrorCode", ErrorCode_name, ErrorCode_value)
}

func init() { proto.RegisterFile("keyexchange.proto", fileDescriptor_keyexchange_8d5592f9a470cb57) }

var fileDescriptor_keyexchange_8d5592f9a470cb57 = []byte{
	// 1981 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x58, 0xdd, 0x6e, 0xdb, 0xc8,
	0x15, 0xb6, 0xec, 0x78, 0x1d, 0x1f, 0xc9, 0x36, 0x35, 0x96, 0x1d, 0x39, 0x9b, 0x38, 0x0a, 0x0b,
	0xb4, 0x5a, 0x17, 0x1b, 0x6c, 0xdc, 0x20, 0x4d, 0x16, 0x41, 0x0b, 0x4a, 0xa2, 0x2c, 0xc1, 0x12,
	0xc5, 0x1d, 0xc9, 0x71, 0x82, 0x02, 0x25, 0xb8, 0xe4, 0x48, 0x22, 0x4c, 0x91, 0xec, 0x90, 0x4a,
	0xac, 0xab, 0x5e, 0x76, 0xfb, 0x04, 0x05, 0x7a, 0xd3, 0xdb, 0x3e, 0x44, 0xfb, 0x26, 0xbd, 0xea,
	0x3b, 0xf4, 0xbe, 0x98, 0xe1, 0xbf, 0x4c, 0x6f, 0x2e, 0x0c, 0x70, 0xbe, 0x73, 0xce, 0x37, 0x67,
	0xce, 0xdf, 0x8c, 0x0c, 0xd5, 0x1b, 0xb2, 0x22, 0xb7, 0xc6, 0x5c, 0x77, 0x66, 0xe4, 0x85, 0x47,
	0xdd, 0xc0, 0x45, 0x3b, 0xbe, 0xe7, 0x06, 0xd6, 0x74, 0x25, 0xfe, 0x77, 0x0b, 0xca, 0x6d, 0xdb,
	0x22, 0x4e, 0xd0, 0x23, 0xb6, 0xed, 0xa2, 0x97, 0x00, 0x3f, 0x2e, 0x2d, 0xdb, 0xd4, 0x2c, 0x67,
	0xea, 0xd6, 0xa1, 0xb1, 0xd9, 0x2c, 0x9f, 0xa3, 0x17, 0x91, 0xf6, 0x8b, 0x16, 0x13, 0xf5, 0x9d,
	0xa9, 0x8b, 0x77, 0x7f, 0x8c, 0x3f, 0xd1, 0x25, 0x1c, 0x4f, 0x2d, 0x67, 0x46, 0xa8, 0x47, 0x2d,
	0x27, 0xf0, 0x35, 0x7f, 0xe9, 0x79, 0x2e, 0x0d, 0x88, 0x59, 0xaf, 0x35, 0xb6, 0x9a, 0xfb, 0xe7,
	0xb5, 0xc4, 0xbc, 0x9b, 0xaa, 0xe1, 0xa3, 0xac, 0xcd, 0x38, 0x36, 0x61, 0x64, 0x06, 0x5d, 0x79,
	0x81, 0xeb, 0x2f, 0xad, 0x80, 0x64, 0xc9, 0x4e, 0xd7, 0xc8, 0xda, 0xa9, 0x1a, 0x3e, 0xca, 0xda,
	0xa4, 0x64, 0x32, 0xd4, 0x3c, 0xf7, 0xb3, 0x6f, 0xcc, 0xc9, 0x22, 0x47, 0xd5, 0xe4, 0x54, 0xe9,
	0xb1, 0xd4, 0x58, 0x09, 0x1f, 0xa6, 0xfa, 0x29, 0xcd, 0x00, 0x90, 0xed, 0xce, 0x2c, 0x47, 0x0b,
	0x77, 0xd1, 0xe6, 0x2c, 0x52, 0xf5, 0x73, 0x1e, 0x9b, 0xd3, 0x84, 0x64, 0xc0, 0x54, 0x42, 0xa7,
	0x78, 0x28, 0xaf, 0x1c, 0xcb, 0x75, 0xb0, 0x60, 0xaf, 0xc1, 0xe8, 0x39, 0x54, 0x0c, 0x1e, 0x70,
	0xcd, 0x71, 0x1d, 0x83, 0xd4, 0xdf, 0x35, 0x36, 0x9b, 0x15, 0x5c, 0x0e, 0x31, 0x85, 0x41, 0xa8,
	0x0e, 0x3b, 0x9e, 0x6e, 0x9a, 0x96, 0x33, 0xab, 0x77, 0x1b, 0xa5, 0x66, 0x05, 0xc7, 0x4b, 0xf4,
	0x0a, 0xca, 0x53, 0xa2, 0x07, 0x4b, 0x4a, 0x34, 0x9f, 0x04, 0x75, 0xb5, 0x51, 0x6a, 0x96, 0xcf,
	0x0f, 0xd3, 0x00, 0x87, 0xb2, 0x31, 0x09, 0x30, 0x4c, 0x93, 0x6f, 0xf1, 0x5f, 0x25, 0xd8, 0x4d,
	0x52, 0x87, 0xce, 0x60, 0xc7, 0xa3, 0xae, 0xb9, 0x34, 0x02, 0x9e, 0xdf, 0xfd, 0x73, 0x21, 0x0d,
	0x44, 0x88, 0xe3, 0x58, 0x01, 0x7d, 0x0f, 0x7b, 0xd1, 0xa7, 0x36, 0xb5, 0xf5, 0x99, 0x1f, 0xa5,
	0xf4, 0x68, 0xdd, 0xa2, 0xcb, 0x84, 0xb8, 0xe2, 0x65, 0x56, 0xe8, 0x5b, 0x78, 0xe8, 0xd9, 0x7a,
	0x30, 0x75, 0xe9, 0xa2, 0x7e, 0xca, 0x37, 0xaa, 0xa6, 0x66, 0x91, 0x00, 0x27, 0x2a, 0xec, 0xd0,
	0x9f, 0x08, 0xf5, 0x2d, 0xd7, 0xa9, 0x37, 0x1b, 0x9b, 0xcd, 0x07, 0x38, 0x5e, 0x8a, 0x53, 0x38,
	0x2a, 0x0c, 0x2e, 0x1a, 0xc2, 0xbe, 0x69, 0x4d, 0xa7, 0x16, 0xe1, 0x29, 0x59, 0xe8, 0x4e, 0x1d,
	0x78, 0x40, 0x7e, 0x59, 0x94, 0x94, 0x0e, 0xd7, 0xec, 0x85, 0x8a, 0x9c, 0x04, 0xef, 0x99, 0x59,
	0x4c, 0xfc, 0x03, 0x3c, 0xfd, 0x59, 0x7d, 0xb4, 0x0f, 0x9b, 0x33, 0x83, 0x07, 0xad, 0x82, 0x37,
	0x67, 0x06, 0x3a, 0x83, 0xaa, 0x4f, 0xe8, 0x27, 0x42, 0xb5, 0x1b, 0xb2, 0xf2, 0xb5, 0x1b, 0xc7,
	0xfd, 0xec, 0xd4, 0x6b, 0x8d, 0xcd, 0xe6, 0x1e, 0x3e, 0x08, 0x05, 0x97, 0x64, 0xe5, 0x5f, 0x32,
	0x58, 0xfc, 0x08, 0x90, 0x66, 0x07, 0x35, 0xa0, 0xac, 0x2f, 0x03, 0x77, 0xe9, 0x99, 0x7a, 0x40,
	0xce, 0xeb, 0xa5, 0x46, 0xa9, 0xf9, 0x10, 0x67, 0x21, 0xf4, 0x0d, 0x08, 0xc6, 0x92, 0x52, 0x56,
	0x27, 0xb6, 0x6b, 0xe8, 0x01, 0x8b, 0xcb, 0x26, 0x57, 0x3b, 0x88, 0xf0, 0x41, 0x04, 0x8b, 0xff,
	0x2e, 0x41, 0x55, 0x52, 0x31, 0xf1, 0x3d, 0xd7, 0xf1, 0xc9, 0x90, 0xf8, 0xbe, 0x3e, 0x23, 0xe8,
	0x1c, 0x76, 0x8d, 0xb9, 0x6e, 0xdb, 0xc4, 0x99, 0x91, 0x28, 0x2e, 0x69, 0xf3, 0x48, 0x6a, 0x3b,
	0x96, 0xe1, 0x54, 0x0d, 0xbd, 0x85, 0x9d, 0xa5, 0x37, 0xa3, 0xba, 0x49, 0xea, 0x35, 0x6e, 0xf1,
	0x2c, 0xb1, 0xb8, 0x0a, 0x71, 0x4c, 0xfe, 0xb4, 0xb4, 0x28, 0x31, 0xa3, 0x5d, 0x70, 0xac, 0x8f,
	0xde, 0x42, 0x25, 0x6c, 0x92, 0xa9, 0x6e, 0xd9, 0xbc, 0x5d, 0x99, 0xfd, 0x71, 0x66, 0x47, 0x1e,
	0xdb, 0x2e, 0x97, 0xe2, 0xb2, 0x9d, 0x2e, 0xc4, 0x9f, 0xb6, 0xa0, 0x9c, 0x71, 0x08, 0x7d, 0x80,
	0xe3, 0x5c, 0xbf, 0x65, 0x8f, 0xc1, 0x7a, 0x4e, 0x2c, 0x4a, 0x6f, 0x62, 0x1e, 0xf6, 0x5d, 0xcd,
	0x2e, 0x10, 0xa1, 0x6b, 0xc8, 0x8e, 0x9d, 0x0c, 0x71, 0x6d, 0x8d, 0x38, 0x33, 0xa9, 0xd6, 0x89,
	0xa7, 0x05, 0x22, 0xf4, 0x7b, 0xd8, 0xf3, 0xdc, 0xcf, 0x19, 0xc2, 0x53, 0x4e, 0xf8, 0x38, 0x33,
	0x62, 0xae, 0xd7, 0x88, 0x2a, 0x9e, 0xfb, 0x39, 0x25, 0xe8, 0x81, 0x70, 0xe7, 0xb4, 0x4d, 0xce,
	0xf1, 0x74, 0x6d, 0xe2, 0xad, 0xd1, 0x1c, 0x18, 0x6b, 0x67, 0x7c, 0x0e, 0x95, 0xa8, 0x28, 0xc3,
	0xf9, 0x72, 0x1e, 0xce, 0x97, 0x10, 0xbb, 0x33, 0x5f, 0xde, 0xe5, 0xe6, 0x8b, 0xe8, 0xc0, 0xc9,
	0xbd, 0x31, 0x45, 0x3f, 0xdc, 0xd3, 0x6e, 0x67, 0x5f, 0x6c, 0xb7, 0xb4, 0xd8, 0xd6, 0x5a, 0xee,
	0xa7, 0x12, 0x3c, 0xff, 0xa2, 0x11, 0xef, 0x3b, 0x3f, 0xe9, 0x3b, 0x1f, 0x7d, 0x07, 0xb5, 0xe8,
	0x88, 0xbe, 0x35, 0x73, 0xc2, 0x71, 0x78, 0x43, 0x56, 0x3c, 0x8b, 0xdb, 0x18, 0x85, 0xb2, 0x71,
	0x2c, 0xba, 0x24, 0x2b, 0x16, 0x94, 0x99, 0x9f, 0x6a, 0xf3, 0xf4, 0x54, 0x70, 0x79, 0xe6, 0x27,
	0x5a, 0xe2, 0x3f, 0x4a, 0x70, 0x72, 0x6f, 0xda, 0xd1, 0x1b, 0xd8, 0x9e, 0x51, 0xdd, 0x8a, 0x8f,
	0x5c, 0x58, 0x29, 0x17, 0x4c, 0x21, 0x3d, 0x6a, 0x68, 0x80, 0x7a, 0x50, 0x9e, 0x2f, 0x74, 0x43,
	0xa3, 0x96, 0x47, 0x16, 0x66, 0xd4, 0x57, 0xbf, 0x2a, 0xb2, 0xef, 0x2d, 0x74, 0x03, 0x73, 0xad,
	0x94, 0x04, 0xe6, 0x09, 0x28, 0x7e, 0x9b, 0x73, 0x30, 0xbf, 0x1b, 0x12, 0x60, 0xeb, 0x86, 0xdc,
	0x44, 0x41, 0x62, 0x9f, 0xe2, 0xef, 0xe0, 0xf4, 0xe7, 0xc9, 0xd1, 0x93, 0xfc, 0x88, 0x60, 0x96,
	0x29, 0x20, 0x8e, 0xa0, 0x7a, 0xa7, 0x6a, 0xd1, 0xf7, 0xb0, 0x3b, 0xd7, 0xfd, 0xb9, 0x66, 0xe8,
	0xfe, 0x3c, 0x8a, 0xc5, 0xd3, 0x6c, 0x91, 0xf7, 0x74, 0x7f, 0xde, 0x66, 0x7f, 0xc9, 0x09, 0x1e,
	0xce, 0x23, 0x48, 0xfc, 0x23, 0xd4, 0x8a, 0x34, 0xd0, 0x31, 0x7c, 0xe5, 0x51, 0x32, 0xb5, 0x6e,
	0x39, 0x61, 0x05, 0x47, 0x2b, 0x86, 0x33, 0x85, 0x60, 0xce, 0x83, 0xb6, 0x8d, 0xa3, 0x15, 0xc3,
	0x03, 0x9d, 0xce, 0x48, 0xc0, 0x87, 0xcc, 0x36, 0x8e, 0x56, 0xe2, 0xdf, 0x4b, 0x50, 0x2b, 0x2c,
	0xdc, 0xb7, 0xb0, 0xe3, 0xcf, 0x75, 0xc7, 0x71, 0xe3, 0xf4, 0x3d, 0x5b, 0xeb, 0xa9, 0x71, 0x28,
	0x4d, 0x9d, 0x8e, 0xf5, 0xd1, 0x05, 0xec, 0x51, 0xe3, 0x95, 0xe6, 0xcf, 0xf5, 0x97, 0x1a, 0x4b,
	0x45, 0x94, 0xbf, 0x5f, 0xac, 0x11, 0x60, 0xe3, 0xd5, 0x78, 0xae, 0xbf, 0x64, 0x41, 0x4e, 0x49,
	0xca, 0x34, 0x45, 0xc5, 0x3a, 0x1c, 0x17, 0xef, 0x25, 0x3e, 0x81, 0xc7, 0xf7, 0x93, 0x88, 0x7f,
	0x29, 0xc1, 0x71, 0xf1, 0xec, 0x45, 0x2f, 0xe0, 0x30, 0x9a, 0xbe, 0xbc, 0xb2, 0x89, 0xa9, 0x79,
	0x3a, 0x0d, 0xa2, 0x44, 0x56, 0x23, 0xd1, 0x98, 0x4b, 0x54, 0x9d, 0x06, 0x2c, 0xdd, 0x69, 0x07,
	0xd4, 0xc2, 0x74, 0x27, 0x00, 0x7a, 0x06, 0xe5, 0x79, 0x10, 0x78, 0x9a, 0xbf, 0x9c, 0xb2, 0x54,
	0xb0, 0xd0, 0xee, 0x62, 0x60, 0xd0, 0x98, 0x23, 0xe2, 0x3f, 0x4b, 0xb0, 0x97, 0x9b, 0xe2, 0xec,
	0xb1, 0x48, 0x28, 0x75, 0xa9, 0x66, 0xb8, 0x26, 0x89, 0x1e, 0x13, 0xe9, 0xab, 0x4a, 0x66, 0xa2,
	0xb6, 0x6b, 0x12, 0xbc, 0x4b, 0xe2, 0x4f, 0xb6, 0x0b, 0x25, 0x01, 0x5d, 0x69, 0x26, 0xb1, 0xf5,
	0x55, 0x94, 0x58, 0xe0, 0x50, 0x87, 0x21, 0x2c, 0xb9, 0xe4, 0xd6, 0xb3, 0xe8, 0x2a, 0x4e, 0x6e,
	0xb8, 0x42, 0xbf, 0x86, 0x6a, 0xb8, 0x97, 0x49, 0x7c, 0x83, 0x5a, 0x5e, 0x10, 0x3e, 0x14, 0x98,
	0x93, 0x02, 0x17, 0x74, 0x52, 0x5c, 0xfc, 0x5f, 0x09, 0x1e, 0x85, 0xaf, 0xda, 0xf8, 0x56, 0x54,
	0x6d, 0xdd, 0x72, 0x02, 0x72, 0x1b, 0xa0, 0x2b, 0x38, 0xca, 0xdd, 0x2e, 0x34, 0xd2, 0x88, 0x2e,
	0x97, 0xe7, 0x45, 0xc3, 0x2c, 0x66, 0x09, 0x47, 0xee, 0xa1, 0x7d, 0x57, 0x82, 0xde, 0x01, 0x1b,
	0xe8, 0x29, 0x5b, 0x78, 0xa3, 0x9c, 0x64, 0x7b, 0x23, 0xcf, 0x52, 0xf6, 0xdc, 0xcf, 0x89, 0xb5,
	0x0c, 0x07, 0xeb, 0xee, 0x84, 0x37, 0xc8, 0x93, 0xf5, 0x42, 0xcb, 0x71, 0xec, 0x1b, 0x39, 0x50,
	0xb4, 0xa1, 0x7e, 0x9f, 0xd7, 0x48, 0xbd, 0x67, 0x7a, 0x7f, 0xf3, 0xc5, 0xe9, 0x1d, 0xf3, 0xac,
	0x0f, 0xef, 0xd7, 0xd0, 0xf8, 0x92, 0x09, 0x42, 0xf0, 0x80, 0xb7, 0x4d, 0x58, 0x94, 0xfc, 0x5b,
	0x1c, 0x82, 0xb0, 0x1e, 0x0d, 0xf4, 0xf6, 0xee, 0x5c, 0x79, 0x52, 0x34, 0x57, 0x12, 0x5f, 0xd2,
	0xb1, 0xf2, 0x1a, 0x0e, 0x0b, 0x14, 0x78, 0x3d, 0x33, 0xc6, 0xa8, 0x9e, 0x43, 0x07, 0x80, 0x41,
	0x51, 0x3d, 0xff, 0xad, 0x04, 0x87, 0x45, 0x81, 0x7a, 0xb3, 0x3e, 0x2d, 0x4e, 0x8b, 0xa7, 0x45,
	0xe2, 0x4a, 0x32, 0x2c, 0xba, 0xc5, 0xc3, 0x42, 0xbc, 0x7f, 0x58, 0x24, 0x1c, 0xb9, 0x59, 0xf1,
	0x2d, 0x1c, 0x15, 0xee, 0x84, 0x6a, 0xb0, 0x6d, 0x2e, 0x17, 0x8b, 0x15, 0x7f, 0x30, 0x6e, 0xe3,
	0x70, 0x21, 0xbe, 0x84, 0x93, 0x7b, 0x89, 0x8b, 0x4d, 0xce, 0xfe, 0x0c, 0x3b, 0xd1, 0xcb, 0x1d,
	0x21, 0xd8, 0x57, 0xf1, 0xa8, 0x73, 0xd5, 0x9e, 0x68, 0xed, 0x41, 0x5f, 0x56, 0x26, 0xc2, 0x06,
	0x3a, 0x06, 0x14, 0x63, 0x83, 0x7e, 0x6b, 0x1c, 0x7a, 0x2f, 0x94, 0xb2, 0xba, 0xc3, 0x51, 0xab,
	0x3f, 0x90, 0x85, 0x4d, 0x74, 0x08, 0x07, 0x31, 0xa6, 0x4a, 0x78, 0xa2, 0xc8, 0x58, 0xd8, 0x42,
	0xcf, 0xe0, 0xeb, 0xbb, 0x04, 0x9a, 0x3c, 0x6c, 0xc9, 0x9d, 0x8e, 0xdc, 0x11, 0xb6, 0xcf, 0x24,
	0xa8, 0x64, 0x7f, 0x3a, 0xa0, 0x23, 0xa8, 0xc6, 0x06, 0xdd, 0x81, 0x74, 0xa1, 0x29, 0x23, 0x45,
	0x16, 0x36, 0xd0, 0x63, 0x38, 0xce, 0xc1, 0x1d, 0xf9, 0xbd, 0xd6, 0xba, 0xea, 0x0f, 0x3a, 0x42,
	0xe9, 0xec, 0x3f, 0x0f, 0xe0, 0x61, 0xfc, 0x3b, 0x82, 0x7b, 0x3c, 0x90, 0x26, 0xdd, 0x11, 0x1e,
	0x6a, 0xd7, 0x7d, 0xe5, 0x37, 0xe7, 0xda, 0x87, 0x37, 0xaf, 0x85, 0x0d, 0x54, 0x03, 0x21, 0xc1,
	0x47, 0xe3, 0x0f, 0x1c, 0x2d, 0xe5, 0xb4, 0x07, 0x7d, 0xe5, 0x2a, 0xc4, 0x37, 0xd1, 0x23, 0x38,
	0x4c, 0xf0, 0xbe, 0xda, 0x1b, 0x29, 0xb2, 0x26, 0xe1, 0xa1, 0xb0, 0x95, 0xa3, 0x19, 0xbf, 0xfe,
	0x8e, 0xa3, 0x0f, 0xee, 0x90, 0xab, 0x6a, 0x5b, 0xd8, 0x46, 0x75, 0xa8, 0x25, 0xa8, 0xa4, 0x74,
	0xf0, 0xa8, 0xdf, 0xe1, 0xfa, 0x5f, 0xa1, 0xaf, 0xe1, 0x51, 0xd6, 0xc9, 0xce, 0xe8, 0x7a, 0xac,
	0xb5, 0xc3, 0x2d, 0x76, 0xd0, 0x09, 0x1c, 0xdd, 0xf5, 0x49, 0x7b, 0xfd, 0x4a, 0x78, 0x98, 0x73,
	0x2b, 0x3a, 0x04, 0x13, 0xec, 0xf2, 0xa8, 0xc5, 0x02, 0x55, 0x1a, 0x0c, 0x39, 0x15, 0xe4, 0xe0,
	0x90, 0x6a, 0xdc, 0x13, 0xca, 0x39, 0xc7, 0xba, 0x58, 0x96, 0x5b, 0xe3, 0x0e, 0x3f, 0x77, 0x25,
	0xe7, 0x58, 0x46, 0xc2, 0x36, 0xd9, 0xcb, 0x09, 0x5b, 0x03, 0xa9, 0x7d, 0xd9, 0x92, 0x31, 0xfe,
	0xc8, 0xb7, 0xda, 0xe7, 0x15, 0x91, 0x04, 0x66, 0xa4, 0x8c, 0xc6, 0xc2, 0x41, 0xce, 0xdd, 0x70,
	0xfb, 0x61, 0x5f, 0x1d, 0x0b, 0x42, 0x41, 0xd8, 0x19, 0x49, 0x35, 0x7f, 0xf4, 0xd1, 0x45, 0x7f,
	0x22, 0xb7, 0x7b, 0x5c, 0x84, 0x72, 0x9b, 0x87, 0x26, 0xdc, 0x85, 0x6e, 0x5f, 0x11, 0x0e, 0x73,
	0xf1, 0xbf, 0x56, 0x7f, 0xcb, 0x4d, 0x6a, 0xb9, 0x5d, 0x46, 0xca, 0xe5, 0xc7, 0x11, 0xc7, 0x8f,
	0x72, 0x6e, 0xfd, 0xa0, 0x7c, 0x50, 0x26, 0xa1, 0xe0, 0x38, 0x47, 0xd3, 0x6a, 0x87, 0xe8, 0xa3,
	0x33, 0x09, 0xca, 0x99, 0xe7, 0x13, 0x8b, 0x69, 0xb7, 0xaf, 0x5c, 0xc8, 0x58, 0xc5, 0x7d, 0x65,
	0xa2, 0x5d, 0x60, 0xa9, 0xaf, 0x08, 0x1b, 0xcc, 0xbf, 0x2c, 0xdc, 0x1b, 0x4a, 0x6d, 0x0d, 0xf7,
	0x55, 0x79, 0xc8, 0x2a, 0xf4, 0x02, 0xca, 0x99, 0xff, 0x52, 0xb0, 0xf8, 0xb7, 0xf1, 0x47, 0x75,
	0x32, 0xd2, 0xc6, 0x57, 0xfd, 0x89, 0xac, 0x8d, 0x7b, 0x92, 0xa2, 0x8c, 0x18, 0xcb, 0x29, 0x3c,
	0xce, 0x49, 0x70, 0xfb, 0x15, 0x93, 0xbe, 0xe4, 0x7c, 0x42, 0xe9, 0xec, 0x14, 0x76, 0x93, 0xff,
	0x51, 0xa0, 0x2a, 0xec, 0xa9, 0xa3, 0x6b, 0xad, 0x27, 0x8d, 0x7b, 0x5a, 0x5b, 0x1a, 0xf7, 0x84,
	0x8d, 0xb3, 0xbf, 0x6e, 0xc2, 0x6e, 0x72, 0xdd, 0x72, 0x05, 0xea, 0x06, 0xae, 0xe1, 0xda, 0x1c,
	0x14, 0x36, 0x90, 0x00, 0x95, 0x09, 0x5d, 0x49, 0x8e, 0x1b, 0xcc, 0x09, 0x95, 0xd4, 0xb0, 0x6d,
	0x5b, 0xba, 0xd9, 0x76, 0x1d, 0x87, 0x18, 0xec, 0xce, 0xec, 0x9b, 0xc2, 0x36, 0x3b, 0xe4, 0x84,
	0xea, 0x9f, 0x88, 0x8d, 0x89, 0x1f, 0x50, 0x8b, 0x0b, 0x84, 0x5d, 0xde, 0x85, 0x94, 0x2c, 0xac,
	0xe5, 0x42, 0x32, 0x0c, 0x77, 0xc9, 0x6e, 0xd5, 0xf0, 0x25, 0x22, 0x94, 0x59, 0x01, 0x30, 0x1e,
	0x4a, 0x4c, 0xe2, 0x04, 0x96, 0x6e, 0xfb, 0x42, 0x85, 0x75, 0x7f, 0xdb, 0x5d, 0xda, 0xa6, 0xe2,
	0x06, 0xef, 0x75, 0xdb, 0x62, 0x3f, 0x68, 0xb3, 0x0a, 0x7b, 0xcc, 0xc3, 0x88, 0x49, 0xbe, 0xb5,
	0xfc, 0xc0, 0x17, 0xf6, 0xd1, 0x53, 0x38, 0x91, 0x6f, 0x03, 0xaa, 0xbf, 0x27, 0xd4, 0x9a, 0x5a,
	0xe1, 0x2f, 0xdb, 0x64, 0x9b, 0x03, 0x66, 0xd1, 0x77, 0x3e, 0x31, 0x32, 0xc9, 0xf3, 0x2e, 0xc9,
	0x4a, 0x10, 0x98, 0xb3, 0x92, 0xe7, 0xd9, 0x91, 0x6e, 0x4b, 0x77, 0x1c, 0x62, 0x0a, 0xd5, 0xff,
	0x07, 0x00, 0x00, 0xff, 0xff, 0x29, 0x21, 0xc9, 0x6e, 0xee, 0x12, 0x00, 0x00,
}
